"""new fields in user model

Revision ID: 504f74adcfe2
Revises: 53917c276095
Create Date: 2019-01-25 14:03:26.103494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504f74adcfe2'
down_revision = '53917c276095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
